id: e9b2ce9132e5464594eb4335ad8c92bf
initial_creation_type: ocr
source_metadata:
  volumes:
    aa15607545de4cf09b3916da9b36f066:
      base_file: v066.txt
      image_group_id: I1PD95912
      title: ''
      total_pages: 1529
      volume_number: 67
